---
title: "Broad Analysis"
author: "Laura Plutowski and Franziska Heinkele"
date: "25 July 2019"
output: html_document
---

```{r, echo=FALSE, message = FALSE, warning = FALSE}
wd = ("C:/Users/franz/Documents/GitHub/project-02-group-05/Broad Analysis")

#wd = ("/Users/laura.plutowski/Desktop/Uni/4.Semester/projekt/project-02-group-05")

library(readr)

Untreated <- readRDS(paste0(wd,"/data/NCI_TPW_gep_untreated.rds"))
Treated <- readRDS(paste0(wd,"/data/NCI_TPW_gep_treated.rds"))
Metadata = read.table(paste0(wd,"/data/NCI_TPW_metadata.tsv"), 
                      header = TRUE, sep ="\t", stringsAsFactors = TRUE)

Treated <- as.data.frame(Treated)
Untreated <- as.data.frame(Untreated)
```

## Searching for batches


```{r, fig.height= 5, fig.width= 7, echo=FALSE}
boxplot(Treated,  
        xlab="samples", ylab="gene expression",
        main= "Gene expression treated samples",
        names= FALSE, xaxt= "n")
```


```{r, fig.height= 5, fig.width= 7, echo=FALSE}
# levels for coloring 
drug <- Metadata$drug
# 15 diffrent colors, for each drug one
palette(rainbow(15))
# Boxplot 
par(mar=c(5, 4, 5, 9))
boxplot(Treated, medcol="black", border = drug, col= drug, 
        xlab="samples", ylab="gene expression",
        main= "Gene expression treated samples colored by drug",
        names= FALSE, xaxt= "n", boxwex=1, boxlty =0)
    
#add a legend to see which color corresponds to which drug:
levels <- as.factor(levels(drug))
legend("topright", inset = c(-0.4,0), legend= levels(drug), xpd = TRUE, pch=19,
       col = levels, title = "Drugs")
```


###Normalization:

```{r}
Treated_norm <- apply(Treated, 2, function(x){
  (x - mean(x)) / sd(x)
})
```

```{r,  fig.height= 5, fig.width= 7, include=FALSE}

Untreated_norm <- apply(Untreated, 2, function(x){
  (x - mean(x)) / sd(x)
})

# repeat creation of boxplot 

# levels for coloring 
drug <- Metadata$drug
palette(rainbow(15))
# Boxplot 
par(mar=c(5, 4, 5, 9))
boxplot(Treated_norm, medcol="black", border = drug, col= drug, 
        xlab="samples", ylab="gene expression",
        main= "Gene expression treated samples with normalized data", 
        names= FALSE, xaxt= "n", boxwex=1, boxlty =0)
    
#add a legend to see which color corresponds to which drug:
levels <- as.factor(levels(drug))
legend("topright", inset = c(-0.4,0), legend= levels(drug), xpd = TRUE, 
       pch=19, col = levels, title = "Drugs")
```


## Principal Component Analysis

```{r, echo=FALSE, message = FALSE, warning = FALSE}
library(readr)
Metadata = read_tsv(paste0(wd,"/data/NCI_TPW_metadata.tsv"))
Metadata <- as.data.frame(Metadata)
FC_norm <- Treated_norm - Untreated_norm
```

```{r, message = FALSE, warning = FALSE}
pca.FC = prcomp(FC_norm)
```


```{r, echo=FALSE}
TreatedrowsMetadata <- grep(Metadata$sample, pattern = "_0nM_", invert = TRUE)
Metadatadrugs <- Metadata[TreatedrowsMetadata,"drug"]

FCwithdrugs <- rbind(FC_norm, Metadatadrugs)
drugfactorFC <- as.factor(FCwithdrugs["Metadatadrugs",])

Marking <- ifelse(Metadata$drug == "vorinostat", "yellow", "black")
```

```{r, fig.height= 7, fig.width= 13, echo=FALSE}
par(mar=c(4, 1, 4, 1), mfrow = c(1, 2))

palette(rainbow(15))
par(mar=c(5, 4, 5, 9)) 
plot(pca.FC$rotation[, 1], pca.FC$rotation[, 2], col = drugfactorFC , pch = 19, xlab = "PC1"
         , ylab = "PC2", main = "PCA FC colored by drugs")

druglevels <- as.factor(levels(drugfactorFC))

legend("topright", inset = c(-0.4,0), levels(drugfactorFC), xpd = TRUE, pch=19,
       col = druglevels, title = "Drugs")

Metadata <-as.data.frame(Metadata)    
Marking <- ifelse(Metadata$drug == "vorinostat", "yellow", "black")

HighlightVorinostat <- cbind(`FC_norm` = Marking)

par(mar=c(5, 4, 5, 9)) 
plot(pca.FC$rotation[, 1], pca.FC$rotation[, 2], col = HighlightVorinostat, pch = 19,
     xlab = "PC1", ylab = "PC2", main = "PCA FC Highlighted Vorinostat samples")
legend("topright", inset = c(-0.4,0), legend = c("Vorinostat","Other drugs"),
       xpd = TRUE, pch=19, col = c("yellow", "black")) 

```
   
   
```{r, fig.height= 5, fig.width= 7, include=FALSE}
Metadata <-as.data.frame(Metadata)    
Marking <- ifelse(Metadata$drug == "vorinostat", "yellow", "black")

HighlightVorinostat <- cbind(`FC_norm` = Marking)


par(mar=c(5, 4, 5, 9))
plot(pca.FC$rotation[, 1], pca.FC$rotation[, 2], col = HighlightVorinostat, pch = 19,
     xlab = "PC1", ylab = "PC2", main = "PCA FC Highlighted Vorinostat samples")
legend("topright", inset = c(-0.3,0), legend = c("Vorinostat","Other drugs"),
       xpd = TRUE, pch=19, col = c("yellow", "black")) 

```



