---
title: 'Correlation Exploration: Heatmaps'
author: "Florencia Zúñiga"
date: "7/10/2019"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r read_data, message = FALSE, warning = FALSE, include=FALSE}
### Loading packages

library(readr)
library(rstudioapi)
library(BBmisc)

#Packages needed for the heatmap
library(pheatmap)
library("DESeq")
library(dendextend)

#Packages for the dendogram
library(ggplot2)
library(circlize)
library(tidyverse)

wd = ("/GitHub/project-02-group-05")

### Reading the data
Untreated <- readRDS(paste0(wd,"/data/NCI_TPW_gep_untreated.rds"))
Treated <- readRDS(paste0(wd,"/data/NCI_TPW_gep_treated.rds"))

Metadata = read.table(paste0(wd,"/data/NCI_TPW_metadata.tsv"), 
                      header = TRUE, sep ="\t", stringsAsFactors = TRUE)

Sensitivity <- readRDS(paste0(wd,"/data/NegLogGI50.rds"))


Basal <- readRDS(paste0(wd,"/data/CCLE_basalexpression.rds"))
Copynumber <- readRDS(paste0(wd,"/data/CCLE_copynumber.rds"))
Mutations <- readRDS(paste0(wd,"/data/CCLE_mutations.rds"))

Metadata = read.table(paste0(wd,"/data/NCI_TPW_metadata.tsv"), header = TRUE, sep ="\t", stringsAsFactors = TRUE)

Cellline_annotation = read.table(paste0(wd,"/data/cellline_annotation.tsv"), 
                                 header = TRUE, sep ="\t", stringsAsFactors = TRUE)
Drug_annotation = read.table(paste0(wd,"/data/drug_annotation.tsv"), 
                             header = TRUE, sep ="\t", stringsAsFactors = TRUE)

### Transforming the data

Treated <- as.data.frame(Treated)
Untreated <- as.data.frame(Untreated)
Sensitivity<- as.data.frame(Sensitivity)


###Data normalization
Untreated_norm <- apply(Untreated, 2, function(x){
  (x - mean(x)) / sd(x)
 })


Treated_norm <- apply(Treated, 2, function(x){
  (x - mean(x)) / sd(x)
 })


FC <- Treated - Untreated
FC_norm <- apply(FC, 2, function(x){
  (x - mean(x)) / sd(x)
 })


### Loading data of the biomarkers                                                                                                    
##  (1)  Creating Vorinostat

#Untreated matrix
UntreatedVorinostatcolumns <- grep(pattern = "vorinostat",colnames(Untreated))

#Same with treated matrix
TreatedVorinostatcolumns <- grep(pattern = "vorinostat",colnames(Treated))

#Define Vorinostat-data: 
UntreatedVorinostat <- Untreated[,UntreatedVorinostatcolumns]
TreatedVorinostat <- Treated[,TreatedVorinostatcolumns]

#fold change matrix 
FC <- TreatedVorinostat - UntreatedVorinostat

#Sensitivity 
vorinostat_Sensitivity_alleZeilen= grep ('vorinostat', rownames(Sensitivity))
vorinostat_Sensitivity_data= Sensitivity[vorinostat_Sensitivity_alleZeilen,]

##  (2)  Creating FC Data -  Finding the Biomarkers

FC <- TreatedVorinostat - UntreatedVorinostat

#We work with mean of the rows because we only want to compare the genes 
FC_meanrow= rowMeans(FC)

## Sorting the data 
#We work with absolute value to find the highest values, 
#because we want to have the most up and down regulated genes.
FC_abs= abs(FC_meanrow)

#We sort the values to get the 100 largest values 
sortedFC_abs <- sort(FC_abs, decreasing = TRUE)
sortedFC_abs <- as.matrix(sortedFC_abs)

#We select the first n for biomarkers 
biomarkers_FC30 = sortedFC_abs[1:30,]
biomarkers_FC30 <- as.matrix(biomarkers_FC30)

biomarkers_FC100 = sortedFC_abs[1:100,]
biomarkers_FC100 <- as.matrix(biomarkers_FC100)

## Creating a matrix with FC values, that are both positive and negative 
FC_both= cbind(FC_meanrow,FC_abs)
FC_both=as.data.frame(FC_both)

#Ordering this matrix 
FC_both_sorted <- FC_both[order(FC_both$FC_abs, decreasing = TRUE),]

#FC values of biomarkers: We select the first 100 of the sorted matrix. 
biomarkers_FC_values30 = FC_both_sorted[1:30,]

biomarkers_FC_values100 = FC_both_sorted[1:100,]

#Removing the absolute values
biomarkers_FC_values30 <- subset( biomarkers_FC_values30, select = -FC_abs)
biomarkers_FC_values30 = as.matrix(biomarkers_FC_values30)

biomarkers_FC_values100 <- subset( biomarkers_FC_values100, select = -FC_abs)
biomarkers_FC_values100 = as.matrix(biomarkers_FC_values100)

```


```{r, include=FALSE}
##### **Creation of a table for 30 biomarkers, with clean column and row names**

# Table
cor1_tab = FC [ which(row.names(FC) %in% rownames(biomarkers_FC_values30)), ]

#Cleaning column and row names
col_names_cor1 = as.data.frame(strsplit(x=colnames(cor1_tab),split="_vorinostat"))
colnames (cor1_tab) = as.data.frame (t(col_names_cor1[1,]))[,1]

row_names_cor1 = as.data.frame(strsplit(x=rownames(cor1_tab),split="///HIST"))
rownames (cor1_tab) = as.data.frame (t(row_names_cor1[1,]))[,1]

#This table can only be read if it is a numerical matrix, so first we check if this is true
cor1_tab = as.matrix(cor1_tab)

class(cor1_tab)

is.numeric(cor1_tab)
```



```{r, include=FALSE}
##### **Creation of a table for 100 biomarkers, with clean column and row names**

# Table
cor1.2_tab = FC [ which(row.names(FC) %in% rownames(biomarkers_FC_values100)), ]

#Cleaning column and row names
col_names_cor1.2    = as.data.frame(strsplit(x=colnames(cor1.2_tab),split="_vorinostat"))
colnames (cor1.2_tab) = as.data.frame (t(col_names_cor1.2[1,]))[,1]

row_names_cor1.2    = as.data.frame(strsplit(x=rownames(cor1.2_tab),split="///HIST"))
rownames (cor1.2_tab) = as.data.frame (t(row_names_cor1.2[1,]))[,1]

#This table can only be read if it is a numerical matrix, so first we check if this is true
cor1.2_tab = as.matrix(cor1.2_tab)

class(cor1.2_tab)

is.numeric(cor1.2_tab)
```


***
##   Heatmaps                                                        
***
###  1. Heatmap with 30 Biomarkers and 59 cell lines                                                      
```{r, include=FALSE}
##### **Tissue Annotation**

tissue <- Metadata[,-c(2:5)] 

row.names(tissue) <- tissue$sample
tissue <- tissue[-c(1)]


tissue = as.data.frame(tissue)
cor1_tissue <- tissue[-c(1:1579), , drop=FALSE] 
cor1_tissue = as.matrix(cor1_tissue)

row_names_cor1_t    = as.data.frame(strsplit(x=rownames(cor1_tissue),split="_vorinostat"))
colnames(cor1_tissue)[colnames(cor1_tissue)=="X786.0"] <- "786.0"
rownames (cor1_tissue) = as.data.frame (t(row_names_cor1_t[1,]))[,1]

names(cor1_tissue)[names(cor1_tissue)=="V1"] <- "Tissue"

cor1_tissue = as.data.frame(cor1_tissue)
```


```{r, fig.align= 'center', include=FALSE}
# Setting colors that are good visivility
cor1_colour = list(tissue = c("Renal" = "#A0E862", 
                       "Lung" = "#29C0DE", 
                       "Breast" = "#005BF8", 
                       "Leukemia" = "#845EC2", 
                       "Colon" = "#CA009E", 
                       "Prostate" = "#FF88CB", 
                       "Ovarian" = "#F1903D", 
                       "Melanoma" = "#FFC75F", 
                       "CNS" = "#F9F871"
                       )
                   )
```

```{r, fig.align= 'center', echo=FALSE}

# Heatmap with annotations and breaks 
cor1 = pheatmap(cor1_tab,
                annotation_colors = cor1_colour,
                annotation_col = cor1_tissue,
                fontsize = 6.5,
                fontsize_row= 5, 
                fontsize_col = 6,
                cutree_rows = 2,
                cutree_cols = 4,
                main = "Heatmap showing 30 biomarkers (y-axis) and 59 cell lines (x-axis)",
                scale = "row"
                )
```


***
###   2. Heatmap with 100 Biomarkers and 59 cell lines
***

```{r, fig.align= 'center', echo=FALSE}
# Heatmap with annotations and breaks 
cor1.2 = pheatmap(cor1.2_tab,
                  annotation_colors = cor1_colour,
                  annotation_col = cor1_tissue,
                  fontsize = 6.5,
                  fontsize_row= 2.7, 
                  fontsize_col = 6,
                  cutree_rows = 2,
                  cutree_cols = 4,
                  main = "Heatmap showing 100 biomarkers (y-axis) and 59 cell lines (x-axis)",
                  scale = "row"
                  )
```


***



